### ISSUE TITLE
grafana-operator metrics

### ISSUE THREAD

**Issue by NissesSenap** [grafana-operator/grafana-operator-experimental#16]
Create metrics for the grafana-operator.
Things like:

- number of dashboards, datasource etc having issues being added to there grafana instance. Since we support many we need to think about labeling.
- How many api calls is done towards the k8s API, how long does it take
- how long does it take to talk to the different grafana API:s?
- How many hits does the dashboard cache get
- etc

This issue will never be perfect but lets start with something and we go from there.

Extra gold star if you also create a cool grafana dashboard that we can ship together with the operator :)

**Comment by weisdd** [comment]
@pb82 I agree with the suggested approach.
