### ISSUE TITLE
[5.0] investigate the Grafana go plugin sdk for writing our own webhook server

### ISSUE THREAD

**Issue by pb82** [grafana-operator/grafana-operator-experimental#18]
Can we extend the Grafana backend and provider a webhook server by using the Go plugin SDK (https://github.com/grafana/grafana-plugin-sdk-go)?

This would allow us to only trigger reconciliation of existing resources when an actual change has happend.

**Comment by NissesSenap** [comment]
All of the sudden i remembered that the grafana team it self is working on some as-code solution.
But it even looks like they are thinking of some kind of k8s controller, so maybe the grafana operator won't be needed in a few years ^^.

https://github.com/grafana/grafana/issues/44450

https://github.com/grafana/grafana/discussions/39593

But upstream changes about webhooks integration will probably get limited intresset from the grafana community.

**Comment by NissesSenap** [comment]
Right now we have decided to go another route. We continuously poll the grafana API. Depending on what happens in the new grafana releases in the future we might reconsider.
