### ISSUE TITLE
instanceSelector required?

### ISSUE THREAD

**Issue by NissesSenap** [grafana-operator/grafana-operator-experimental#21]
Is there any reasons why not to make instanceSelector required?

This applies to all resources that we have created.

```shell
➜ k explain grafanadashboards.grafana.integreatly.org.spec
KIND:     GrafanaDashboard
VERSION:  grafana.integreatly.org/v1beta1

RESOURCE: spec <Object>

DESCRIPTION:
     <empty>

FIELDS:
   instanceSelector	<Object>
   json	<string>
   plugins	<[]Object>
```

**Comment by pb82** [comment]
I think we can make it required. Without an instance selector those resources will be ignored. If you want to create a resource but not import it anywhere at this time, you could set the instance selector to a non-existing value.

**Comment by NissesSenap** [comment]
I think this was solved in: https://github.com/grafana-operator/grafana-operator-experimental/pull/43
