### ISSUE TITLE
Ingress kind gives `ingress is not ready`

### ISSUE THREAD

**Issue by NissesSenap** [grafana-operator/grafana-operator-experimental#50]
Using `examples/basic/resources.yaml`
I get

```shell
1.6713644067525926e+09  ERROR   reconciler error in stage       {"controller": "grafana", "controllerGroup": "grafana.integreatly.org", "controllerKind": "Grafana", "Grafana": {"name":"grafana","namespace":"grafana-operator-system"}, "namespace": "grafana-operator-system", "name": "grafana", "reconcileID": "5a10f411-13ad-4d57-9200-c0a39d3f5d24", "stage": "ingress", "error": "ingress is not ready yet"}
```

Probably something simple that I have missed in my kind/ingress and all I guess we need to do is to write some docs around it.

**Comment by NissesSenap** [comment]
ping @weisdd

**Comment by weisdd** [comment]
@NissesSenap that's expected, because the example yaml has preferIngress set, though doesn't contain an ingress spec with a host in it.

**Comment by NissesSenap** [comment]
Well that makes allot of sense. Thanks for the explanation and the quick reply.
