### ISSUE TITLE
grafana instance with same label don't get datasource after initial trigger

### ISSUE THREAD

**Issue by NissesSenap** [grafana-operator/grafana-operator-experimental#54]
So I realized that we don't have any way of re-triggering a new grafana instance that gets created with the same label as another instance.

Say that we have `grafana` below together with a random  `GrafanaDatasource`

```.yaml
apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  labels:
    dashboards: "grafana"
spec:
  client:
    preferIngress: false
  config:
    log:
      mode: "console"
    auth:
      disable_login_form: "false"
    security:
      admin_user: root
      admin_password: secret
----
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: grafanadatasource-sample
spec:
  instanceSelector:
    matchLabels:
      dashboards: "grafana"
  plugins:
    - name: grafana-clock-panel
      version: 1.3.0
  datasource:
    name: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus-service:9090
    isDefault: true
    jsonData:
      'tlsSkipVerify': true
      'timeInterval': "5s"
    editable: false

```

When the operator have reconciled both of them and the dashboard is applied to the grafana instance.
What happens if you create a new grafana instance with the same label selector. It should apply that dashboard to the new grafana instance as well.

But we don't have any reconciler that tells the grafanadatasource that it should trigger a new reconcile.

```.yaml
apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana-b
  labels:
    dashboards: "grafana"
spec:
  client:
    preferIngress: false
  config:
    log:
      mode: "console"
    auth:
      disable_login_form: "false"
    security:
      admin_user: root
      admin_password: secret
  ingress:
    spec:
      ingressClassName: nginx
      rules:
        - host: test.io
          http:
            paths:
              - backend:
                  service:
                    name: grafana-service
                    port:
                      number: 3000
                path: /
                pathType: Prefix
```

So other then it's a bug is this realistic that it would happen.
And I think the answer is maybe. 
I can defiantly see some big org wanting the same datasource on multiple grafana instances and applying that with a simple label is the way to go and probably a new grafana instance would be created after some time if a new team is created or something like that.

Not the end of the world but it would be good to support this use case.

**Comment by NissesSenap** [comment]
Second thoughts (don't have time to read code).
While at the subject of reconciliation what happens if a grafana pod is restarted.
How will the controller know that it should apply data to the deployment again?
I assume that this works in v4 I just don't know how from the top of my head.

**Comment by pb82** [comment]
Reconciliation will happen every 5 minutes for dashboards and data sources. So in the worst case a user would have to wait that long. The period can be configured.
