### ISSUE TITLE
[5.0] grafana datasource managed through API

### ISSUE THREAD

**Issue by NissesSenap** [grafana-operator/grafana-operator-experimental#6]
From https://github.com/grafana-operator/grafana-operator/blob/master/documentation/roadmap/roadmap-v5.md

As part of 5.0 we would like to see grafanadatasources to be managed by the grafana API instead of using a configmap that is mounted in the the grafana instance.

**Comment by NissesSenap** [comment]
When implementing this feature think of that there are plugins that creates custom fields for datasrouces, we will never be able to support all of them in the CRD.

One solution could be `map[string]string` https://github.com/grafana-operator/grafana-operator/issues/708

**Comment by pb82** [comment]
Datasource are now supported and users can specify arbitrary properties for `jsonData` and `secureJsonData`.
