### ISSUE TITLE
v5.0.0-rc

### ISSUE THREAD

**Issue by pb82** [grafana-operator/grafana-operator-experimental#63]
missing features for v5.0.0-rc
- [x] datasource env vars
- [ ] website with documentation https://github.com/grafana-operator/grafana-operator-experimental/issues/64
- [ ] manifest overlays to produce both namespaced and cluster scoped resources
- [x] e2e tests, at least some unit tests
- [ ] jsonnet and grafonnet support https://github.com/grafana-operator/grafana-operator-experimental/issues/67

**Comment by NissesSenap** [comment]
I close this issue since we use milstones instead.
