### ISSUE TITLE
[5.0] align routes and ingress

### ISSUE THREAD

**Issue by NissesSenap** [grafana-operator/grafana-operator-experimental#9]
From https://github.com/grafana-operator/grafana-operator/blob/master/documentation/roadmap/roadmap-v5.md
As part of 5.0 we would like to see the same configuration options available in both route and ingress, e.g. no TLS options exposed for Routes.

At the same time we would like to use the power of openshift when it's phaseable.
Today we assume routes should be behind TLS by default. This is very simple to do in OCP.

Since we don't know enough about none OCP environments we can't do the same assumptions. Instead the default value for ingress should be http.
We have already implemented was of making differences between OCP and none OCP and we should use them to solve the same issue here.

**Comment by pb82** [comment]
We now expose the Kube objects themselves and users can configure all properties.
